sudo: required
services:
  - docker

before_install:
  - docker build -t timdinia/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true timdinia/docker-react yarn test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: eu-west-3
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-eu-west-3-209313652649"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  edge: true
